//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canditate_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Canditate_info()
        {
            this.assigned_user_exam = new HashSet<assigned_user_exam>();
            this.Edu_tbl1 = new HashSet<Edu_tbl>();
            this.User_Exam_Answer = new HashSet<User_Exam_Answer>();
            this.work_tbl1 = new HashSet<work_tbl>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Cell_no { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
        public string CNIC { get; set; }
        public int edu_dtl { get; set; }
        public int work_exp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assigned_user_exam> assigned_user_exam { get; set; }
        public virtual Edu_tbl Edu_tbl { get; set; }
        public virtual work_tbl work_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Edu_tbl> Edu_tbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Exam_Answer> User_Exam_Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work_tbl> work_tbl1 { get; set; }
    }
}
