//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edu_dtl_tbl
    {
        public int Id { get; set; }
        public int edu_id { get; set; }
        public string Passing_year { get; set; }
        public string Grade { get; set; }
        public string Percentage { get; set; }
    
        public virtual Edu_tbl Edu_tbl { get; set; }
    }
}
