//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities1 : DbContext
    {
        public Database1Entities1()
            : base("name=Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assigned_user_exam> assigned_user_exam { get; set; }
        public virtual DbSet<Canditate_info> Canditate_info { get; set; }
        public virtual DbSet<Course_tbl> Course_tbl { get; set; }
        public virtual DbSet<Edu_tbl> Edu_tbl { get; set; }
        public virtual DbSet<Exam_Schedule> Exam_Schedule { get; set; }
        public virtual DbSet<Manager_info> Manager_info { get; set; }
        public virtual DbSet<Question_bank> Question_bank { get; set; }
        public virtual DbSet<User_Exam_Answer> User_Exam_Answer { get; set; }
        public virtual DbSet<work_dtl_tbl> work_dtl_tbl { get; set; }
        public virtual DbSet<work_tbl> work_tbl { get; set; }
        public virtual DbSet<edu_dtl_tbl> edu_dtl_tbl { get; set; }
    }
}
