//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Exam_Answer
    {
        public int Id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public string Answer { get; set; }
        public Nullable<int> Question_id { get; set; }
        public Nullable<int> Marks { get; set; }
    
        public virtual Canditate_info Canditate_info { get; set; }
        public virtual Exam_Schedule Exam_Schedule { get; set; }
        public virtual Question_bank Question_bank { get; set; }
    }
}
