//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_dtl_tbl
    {
        public int Id { get; set; }
        public int work_id { get; set; }
        public string Company_name { get; set; }
        public string Job_title { get; set; }
        public string Start_year { get; set; }
        public string End_year { get; set; }
        public string Job_description { get; set; }
    
        public virtual work_tbl work_tbl { get; set; }
    }
}
